
name: Run Script

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

jobs:
  build-from-prebuilt:
    runs-on: self-hosted

    steps:
    
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Download YouTube apk
        run: |
          mkdir "build"
          cd "build"
          wget -q "https://github.com/CnC-Robert/revanced-cli-script/releases/download/stock-yt-17.19.36/youtube.apk"
          cd ..
      
      - name: Execute script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./build-from-prebuilt.sh
          ROOT=1 ./build-from-prebuilt.sh
          ls
